### ISSUE TITLE
Can't connect since using this

### ISSUE THREAD

**Issue by p1r473** [jbob182/pia-openvpn-wrapper#2]
I replaced openvpn with your patched version, now the PIA tray icon stays red and won't connect.

**Comment by jbob182** [comment]
Did you rename openvpn.exe to openvpn-orig.exe ? The wrapper requires that file to be renamed.

**Comment by p1r473** [comment]
I renamed it to openvpn.exe.bak
I didn't realize it was specifially openvpn-orig.exe, sorry
