### ISSUE TITLE
Possible Unclear Instructions

### ISSUE THREAD

**Issue by luckyllama** [jbob182/pia-openvpn-wrapper#3]
Perhaps change the documentation to make the following line more explicit: 

    Rename the openvpn.exe file in the pia_manager folder to openvpn-orig.exe

I read that as "rename the file to something else so it won't execute" so I renamed it to "openvpn-backup.exe" which, I now know, doesn't work. It would've saved me some effort (spent re-installing PIA and finally reading the source code) if the instructions had a more clear message. 

    Rename the openvpn.exe file in the pia_manager folder to openvpn-orig.exe (the file will still be used and it must be exactly that filename)

Otherwise, thanks for figuring this out and writing this!

**Comment by jbob182** [comment]
Good idea, that instruction is unclear. I've updated the readme.
